---
# Setting Log Levels          
logging.level:
  com.sap: DEBUG                      # set SAP-class loggers to DEBUG.
  org.springframework: ERROR          # set to DEBUG to see all beans loaded and auto-config conditions met.
  org.springframework.security: DEBUG # set to ERROR for production setups. 
  org.springframework.web: DEBUG      # set to ERROR for production setups.
          
# Server Port (from environment or 8080 if not set).          
server:
  port: ${PORT:8080}

# Enable to make Spring Boot log debug information.
# debug: true


xsuaa:
  xsappname: ${vcap.services.xsuaa-authn.credentials.xsappname}
  uaadomain: ${vcap.services.xsuaa-authn.credentials.uaadomain}
  clientid: ${vcap.services.xsuaa-authn.credentials.clientid}
  url: ${vcap.services.xsuaa-authn.credentials.url}

identity:
  clientid: ${vcap.services.ias-authn.credentials.clientid}
  domain: ${vcap.services.ias-authn.credentials.domain}